<?php

declare (strict_types=1);
namespace Doctrine\DBAL\Driver\Exception;

use Doctrine\DBAL\Driver\Abstract_Exception;
use Throwable;
/** @internal */
final class No_Identity_Value extends Abstract_Exception
{
    public static function new(?Throwable $previous = null): self
    {
        return new self('No identity value was generated by the last statement.', null, 0, $previous);
    }
}